### ISSUE TITLE
To run this application, you must install missing frameworks for.NET

### ISSUE THREAD

**Issue by Esekash** [GlowPuff/ICEditor#13]
Hi, when I try to launch the app, I always receive this message "To run this application, you must install missing frameworks for.NET" The link takes meto the Download .NET 6.0 Runtime web, I download and install it, but the problem continues. Any idea?
I have Windows 11 Pro O.S

Thanks

**Comment by GlowPuff** [comment]
Hmm, just to confirm, it's the .NET download from this page?

- https://dotnet.microsoft.com/en-us/download/dotnet/6.0

It might be that you downloaded and installed the .NET SDK (SDK 6.0.300) or the ".NET Runtime 6.0.5" instead of ".NET Desktop Runtime 6.0.5".  You specifically need the **DESKTOP** runtime.

**Comment by Esekash** [comment]
Hi, I install for the first time the update that the link takes me (sorry im not english and its dificult for me to explain) then I install feww other versions, but now I install the one you say to me (.NET 6.0 SDK (v6.0.300) ) and it works fine, so thank you and my apologize for you to make you lost your precious time :).You are doing a great work.
