### ISSUE TITLE
Suggestions: Interface

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ICEditor#7]
Here are some suggestions for interface improvements.

List vs. Dropdown: Currently, whenever I can select something from a list, a dropdown menu is used. I think using a list instead of a dropdown menu would lead to a clearer layout and make it easier to find what you're looking for. Instances where I would have found a list more practical: 
- The list of triggers to the left of the main interface.
- The list of events to the left of the main interface.
- The "All Entities" list in the map editor.
- The "Event actions" list when creating an event.

Deployment event action: I have two suggestions to make this even easier to use.
- "Can be reinforced" and "Can be redeployed" should be active by default, only on very rare occasions is this not the case. 
- Is there a way to easily filter between groups already set as initial/reserved? This would make it easier to actually pick the reserved groups.

Copy events: If you could find a way to easily copy created events, this would be awesome. In the current mission, I had to create 4 very similar events. This wasn't much of a problem, but re-creating more complex events could be a chore. It's not necessary, though, of course.

**Comment by GlowPuff** [comment]
All these are now in.

- Triggers and Events are now lists instead of dropdowns, but I left the other two as-is (for now).
- The Deployment event now filters its list when Initial/Reserved is set as the type.
- Each map entity now has a "Duplicate" button to copy/paste it into the map with a small offset so it's easy to see the new one.
